### ISSUE TITLE
System Mouse Can Click Outside Skyrim Window And Change Focus

### ISSUE THREAD

**Issue by OnigiriOni** [ArranzCNL/ImprovedCameraAE#16]
With this mod active the system mouse is, when using a multi-monitor setup, not only scrolling windows on different monitors, which is normal Skyrim behavior, but is now completely free to click anywhere and change the application focus.

Once this mod is disabled the system mouse is invisible and cannot remove the focus from the Skyrim window. It still moves outside of the window but that is normal behavior.

Having Skyrim run in borderless window or fullscreen does not change anything.

**Comment by ArranzCNL** [comment]
Issue should be resolved in upcoming build. Backend for this had to be redesigned and found a last minute issue earlier today with the skyrim window if it slightly hangs due to heavy load the mouse becomes free to roam around which is fixed.

I'll leave this open to see if anymore problems arise with this when AE PR2 is out.
