### ISSUE TITLE
Don't understand how to install

### ISSUE THREAD

**Issue by Defucota** [ArranzCNL/ImprovedCameraAE#33]
Like the topic says, I really don't understand how to install this mod.
I'm stuggling since yesterday
Thanks

**Comment by Octobread** [comment]
As far as I know, this repository is apparently deprecated. The [Release page for this Repo](https://github.com/ArranzCNL/ImprovedCameraAE/releases) says:

>This repo will be removed in the future due to being surplus to requirements:
>For latest AE build please use:
>[ImprovedCameraSE](https://github.com/ArranzCNL/ImprovedCameraSE/releases/tag/v1.0.0)

To my knowledge, you're supposed to use the version listed there instead. I have it running myself (although not the latest version - will try that later at some point) and it runs just fine for the anniversary edition (besides it apparently being the repository for the SE version).

So you should try the "SE" version instead. From the top of my head, the following steps should work:

1. Download the latest release (_ImprovedCameraSE-1.0.0.PR5.7z_) from [the SE repo](https://github.com/ArranzCNL/ImprovedCameraSE/releases/tag/v1.0.0)
2. [The latest Skyrim version is not yet supported](https://github.com/ArranzCNL/ImprovedCameraSE/issues/42). So you'll have to make sure you run Skyrim version **1.6.353** (AE) first and [downgrade your game with this tool](https://www.nexusmods.com/skyrimspecialedition/mods/57618), if needed.
3. Unzip the archive
4. You'll find a `1.5` and a `1.6` folder in there. To be honest, I don't know what they're for. So maybe try and copy-pasting the contents of `1.6` into your `Data\` directory and see if it works. If not, try again with the contents of the `1.5` directory of the archive.

I think it goes without saying that you'll need [SKSE64](https://skse.silverlock.org/) for this mod to work. Make sure, you pick the right version for your game. For Skyrim `1.6.353` it should be SKSE version `2.1.5` which you can find in the [SKSE archive](http://skse.silverlock.org/download/archive/).

Let me know, if this worked for you. I may not be able to check back right away though, since I'll be at work for today.
